import type { ErrorClass, RuleBook } from "./types";

/**
 * One enrichment run: 830 SKUs from a 4,100-SKU electrical catalog, grouped into
 * error classes by field × failure mode × source tier. Synthetic data modeled on
 * electrical/industrial distribution catalogs (NEMA, AWG, UNSPSC, UL/CSA).
 */
export const CLASSES: ErrorClass[] = [
  {
    id: "volt",
    lane: "auto",
    field: "Voltage",
    rows: 1842,
    title: "Voltage strings normalized to a single unit form",
    failure: "unit-format",
    src: "Manufacturer spec PDF",
    tier: 1,
    corrob: 3,
    why: "Deterministic transform with a closed output set. Three tier-1 sources agree on the numeral; only the suffix varies.",
    samples: [
      { sku: "HBL5361", product: "Hubbell 20A duplex receptacle", current: "125 volts", proposed: "125 V", source: "Hubbell spec sheet HBL5361.pdf, p.1", tier: 1 },
      { sku: "EAT-BR120", product: "Eaton BR single-pole breaker", current: "120V AC", proposed: "120 V", source: "Eaton catalog BR-series, table 3", tier: 1 },
      { sku: "SQD-QO115", product: "Square D QO 15A breaker", current: "120/240 Volts", proposed: "120/240 V", source: "Schneider QO spec 0730CT9201", tier: 1 },
    ],
  },
  {
    id: "mfr",
    lane: "auto",
    field: "Manufacturer",
    rows: 1204,
    title: "Manufacturer aliases collapsed to the canonical entity",
    failure: "entity-alias",
    src: "Internal alias table + mfr site",
    tier: 1,
    corrob: 2,
    why: "Alias resolution against a maintained entity table, not inference. Unmapped strings fall through to review rather than guessing.",
    samples: [
      { sku: "SQD-QO120", product: "QO 20A breaker", current: "SQ. D", proposed: "Square D", source: "schneider-electric.com brand registry", tier: 1 },
      { sku: "SQD-HOM230", product: "Homeline 30A 2-pole", current: "SCHNEIDER/SQUARE-D", proposed: "Square D", source: "schneider-electric.com brand registry", tier: 1 },
      { sku: "THN-3502", product: "Thomas & Betts 1/2 in connector", current: "T&B", proposed: "ABB Installation Products", source: "abb.com brand history page", tier: 1 },
    ],
  },
  {
    id: "nema",
    lane: "auto",
    field: "Enclosure Rating",
    rows: 946,
    title: "NEMA enclosure ratings snapped to the published enum",
    failure: "enum-drift",
    src: "Manufacturer spec PDF",
    tier: 1,
    corrob: 2,
    why: "Target values are a fixed NEMA list. Anything that does not land exactly on a list member is demoted, not coerced.",
    samples: [
      { sku: "HOF-A1210", product: "Hoffman wall-mount enclosure", current: "NEMA-12", proposed: "NEMA 12", source: "nVent Hoffman A-series catalog p.44", tier: 1 },
      { sku: "HOF-A16148", product: "Hoffman wash-down enclosure", current: "4x", proposed: "NEMA 4X", source: "nVent Hoffman spec A16148SS6", tier: 1 },
      { sku: "CRS-EDS271", product: "Crouse-Hinds junction box", current: "Type 3R Rainproof", proposed: "NEMA 3R", source: "Eaton Crouse-Hinds EDS datasheet", tier: 1 },
    ],
  },
  {
    id: "awg",
    lane: "auto",
    field: "Conductor Size",
    rows: 733,
    title: "Conductor sizes normalized to AWG notation",
    failure: "unit-format",
    src: "Manufacturer spec PDF",
    tier: 1,
    corrob: 2,
    why: "Closed numeric set with a fixed suffix. Kcmil sizes are routed separately rather than forced into AWG.",
    samples: [
      { sku: "SOU-58021", product: "Southwire THHN stranded", current: "#12 AWG", proposed: "12 AWG", source: "southwire.com THHN spec sheet", tier: 1 },
      { sku: "SOU-11587", product: "Southwire NM-B 14/2", current: "14ga", proposed: "14 AWG", source: "southwire.com NM-B product page", tier: 1 },
      { sku: "ENC-C1102", product: "Encore XHHW-2 copper", current: "No. 10", proposed: "10 AWG", source: "Encore Wire XHHW-2 datasheet", tier: 1 },
    ],
  },
  {
    id: "amp",
    lane: "auto",
    field: "Ampacity",
    rows: 1105,
    title: "Ampacity extracted from spec-sheet rating tables",
    failure: "pdf-table-extract",
    src: "Manufacturer spec PDF",
    tier: 1,
    corrob: 2,
    why: "Cell-level extraction with the source table cited. Two independent documents must return the same figure or the row demotes.",
    samples: [
      { sku: "EAT-BR230", product: "Eaton BR 30A 2-pole", current: "—", proposed: "30 A", source: "Eaton BR catalog, ratings table row 14", tier: 1 },
      { sku: "SQD-QO260", product: "QO 60A 2-pole", current: "—", proposed: "60 A", source: "Schneider 0730CT9201, table 2", tier: 1 },
      { sku: "SIE-Q2100", product: "Siemens QP 100A 2-pole", current: "—", proposed: "100 A", source: "Siemens QP datasheet, p.2", tier: 1 },
    ],
  },
  {
    id: "weight",
    lane: "auto",
    field: "Shipping Weight",
    rows: 612,
    title: "Weights converted to pounds at two decimals",
    failure: "unit-convert",
    src: "Manufacturer spec PDF",
    tier: 1,
    corrob: 2,
    why: "Pure arithmetic on a cited figure. The model never supplies a weight it did not read.",
    samples: [
      { sku: "HOF-A1210", product: "Hoffman wall-mount enclosure", current: "5.4 kg", proposed: "11.90 lb", source: "nVent Hoffman A-series catalog p.44", tier: 1 },
      { sku: "CRS-EDS271", product: "Crouse-Hinds junction box", current: "1,240 g", proposed: "2.73 lb", source: "Eaton Crouse-Hinds EDS datasheet", tier: 1 },
      { sku: "HBL5361", product: "Hubbell duplex receptacle", current: "0.19 lbs.", proposed: "0.19 lb", source: "Hubbell spec sheet HBL5361.pdf", tier: 1 },
    ],
  },
  {
    id: "upc",
    lane: "auto",
    field: "UPC",
    rows: 488,
    title: "11-digit UPCs padded and check-digit validated",
    failure: "checksum",
    src: "GS1 / manufacturer packaging",
    tier: 1,
    corrob: 2,
    why: "The check digit is a verifiable mathematical fact, so this class is self-proving. A failed checksum is held, never written.",
    samples: [
      { sku: "SOU-58021", product: "Southwire THHN stranded", current: "03278958021", proposed: "032789580219", source: "GS1 GTIN registry lookup", tier: 1 },
      { sku: "SIE-Q2100", product: "Siemens QP 100A 2-pole", current: "78362117694", proposed: "783621176941", source: "Siemens packaging artwork", tier: 1 },
      { sku: "HBL5361", product: "Hubbell duplex receptacle", current: "78367820663", proposed: "783678206630", source: "GS1 GTIN registry lookup", tier: 1 },
    ],
  },
  {
    id: "conduit",
    lane: "auto",
    field: "Trade Size",
    rows: 402,
    title: "Conduit trade sizes normalized to decimal inches",
    failure: "unit-format",
    src: "Manufacturer catalog",
    tier: 1,
    corrob: 2,
    why: "Trade size is a naming convention, not a measurement — kept as the trade designation with the fraction resolved for filter sorting.",
    samples: [
      { sku: "ALL-58012", product: "Allied EMT conduit", current: "3/4\"", proposed: "0.75 in (trade)", source: "Allied Tube EMT catalog p.7", tier: 1 },
      { sku: "ALL-58014", product: "Allied EMT conduit", current: "1-1/4 inch", proposed: "1.25 in (trade)", source: "Allied Tube EMT catalog p.7", tier: 1 },
      { sku: "THN-3502", product: "T&B EMT connector", current: "one half", proposed: "0.50 in (trade)", source: "ABB TB catalog, fittings section", tier: 1 },
    ],
  },
  {
    id: "schema",
    lane: "review",
    field: "Diameter / Width / OD",
    rows: 918,
    title: "Three source fields competing for one catalog attribute",
    failure: "schema-collision",
    src: "Mixed manufacturer sheets",
    tier: 1,
    corrob: 1,
    why: "Manufacturers publish the same measurement as Diameter, Outside Diameter and Width. Merging them is a taxonomy decision with webstore filter consequences — a steward makes it once, for the family, not 918 times.",
    samples: [
      { sku: "ALL-58012", product: "Allied EMT conduit", current: "Outside Diameter 0.922 in", proposed: "Diameter 0.922 in", source: "Allied Tube EMT catalog p.7", tier: 1 },
      { sku: "CAR-E942H", product: "Carlon PVC elbow", current: "Width 1.05 in", proposed: "Diameter 1.05 in", source: "Carlon PVC fittings guide", tier: 1 },
      { sku: "SOU-58021", product: "Southwire THHN stranded", current: "O.D. 0.130 in", proposed: "Diameter 0.130 in", source: "southwire.com THHN spec sheet", tier: 1 },
    ],
  },
  {
    id: "temp",
    lane: "review",
    field: "Temperature Rating",
    rows: 264,
    title: "Two tier-1 sources disagree on the same rating",
    failure: "source-conflict",
    src: "Spec sheet vs. print catalog",
    tier: 1,
    corrob: 0,
    why: "The spec sheet says 90°C dry, the print catalog says 75°C wet — both are correct for different conditions and the catalog has one field. The fix is a schema change, which is exactly the kind of thing that should surface to a human.",
    samples: [
      { sku: "SOU-58021", product: "Southwire THHN stranded", current: "90°C", proposed: "90°C dry / 75°C wet", source: "Spec sheet p.1 vs. catalog table 4", tier: 1 },
      { sku: "ENC-C1102", product: "Encore XHHW-2 copper", current: "75°C", proposed: "90°C dry / 75°C wet", source: "Encore datasheet vs. 2025 catalog", tier: 1 },
      { sku: "SOU-11587", product: "Southwire NM-B 14/2", current: "60°C", proposed: "60°C (NM-B terminated)", source: "NEC 334.80 vs. conductor rating", tier: 1 },
    ],
  },
  {
    id: "material",
    lane: "review",
    field: "Enclosure Material",
    rows: 377,
    title: "Material inferred from the description, not read from a source",
    failure: "no-citation",
    src: "Product description text",
    tier: 2,
    corrob: 0,
    why: "“SS6” in a part number very probably means 316 stainless. Probably is not a citation. These are correct often enough to be dangerous, which is the definition of a review-lane class.",
    samples: [
      { sku: "HOF-A16148SS6", product: "Hoffman wash-down enclosure", current: "—", proposed: "316 Stainless Steel", source: "Inferred from suffix SS6 in part number", tier: 2 },
      { sku: "HOF-A1210CHNFSS", product: "Hoffman hinged enclosure", current: "—", proposed: "304 Stainless Steel", source: "Inferred from suffix SS in description", tier: 2 },
      { sku: "CAR-E942H", product: "Carlon PVC elbow", current: "—", proposed: "PVC", source: "Inferred from product line name", tier: 2 },
    ],
  },
  {
    id: "desc",
    lane: "review",
    field: "Long Description",
    rows: 1530,
    title: "Descriptions exceed the ERP field limit and need a truncation policy",
    failure: "channel-format",
    src: "Generated from enriched attributes",
    tier: 2,
    corrob: 0,
    why: "The webstore takes 2,000 characters, the ERP takes 240, and the EDI feed takes 80. This is one policy decision about what gets dropped first, applied 1,530 times — not 1,530 editorial calls.",
    samples: [
      { sku: "HBL5361", product: "Hubbell duplex receptacle", current: "412 chars", proposed: "Truncate at last full clause ≤240", source: "Generated from 15 enriched attributes", tier: 2 },
      { sku: "HOF-A1210", product: "Hoffman wall-mount enclosure", current: "388 chars", proposed: "Truncate at last full clause ≤240", source: "Generated from 12 enriched attributes", tier: 2 },
      { sku: "SQD-QO115", product: "Square D QO 15A breaker", current: "301 chars", proposed: "Truncate at last full clause ≤240", source: "Generated from 14 enriched attributes", tier: 2 },
    ],
  },
  {
    id: "coo",
    lane: "hold",
    field: "Country of Origin",
    rows: 311,
    title: "Country of origin scraped from a marketplace listing",
    failure: "untrusted-source",
    src: "Third-party marketplace listing",
    tier: 3,
    corrob: 0,
    why: "Origin drives tariff exposure and customs declarations. A third-party reseller listing is not a source of record for it, at any confidence. Held regardless of how sure the model is.",
    samples: [
      { sku: "SIE-Q2100", product: "Siemens QP 100A 2-pole", current: "—", proposed: "Mexico", source: "Amazon listing, seller-supplied field", tier: 3 },
      { sku: "ALL-58012", product: "Allied EMT conduit", current: "—", proposed: "USA", source: "Distributor webstore, uncited", tier: 3 },
      { sku: "CAR-E942H", product: "Carlon PVC elbow", current: "—", proposed: "USA", source: "Marketplace listing, seller-supplied", tier: 3 },
    ],
  },
  {
    id: "unspsc",
    lane: "hold",
    field: "UNSPSC Code",
    rows: 209,
    title: "Classification codes generated with no source document",
    failure: "model-generated",
    src: "No citation",
    tier: 3,
    corrob: 0,
    why: "UNSPSC feeds customer punchout catalogs and tax treatment. A plausible-looking eight-digit code with no source is the single worst failure mode in this dataset, because nothing downstream will question it.",
    samples: [
      { sku: "HOF-A1210", product: "Hoffman wall-mount enclosure", current: "—", proposed: "39121608", source: "Model output, no source document", tier: 3 },
      { sku: "THN-3502", product: "T&B EMT connector", current: "—", proposed: "39121409", source: "Model output, no source document", tier: 3 },
      { sku: "ALL-58014", product: "Allied EMT conduit", current: "—", proposed: "39121701", source: "Model output, no source document", tier: 3 },
    ],
  },
  {
    id: "ul",
    lane: "hold",
    field: "Safety Listing",
    rows: 146,
    title: "UL / CSA listings not found on the certifying body's register",
    failure: "unverified-claim",
    src: "Manufacturer marketing page",
    tier: 2,
    corrob: 0,
    why: "A safety listing is a legal claim. If it is not in UL Product iQ under that file number, the product does not publish it — and the steward gets told which register was checked and when.",
    samples: [
      { sku: "CRS-EDS271", product: "Crouse-Hinds junction box", current: "—", proposed: "UL 1203 listed", source: "Marketing page; not in UL Product iQ", tier: 2 },
      { sku: "HOF-A16148SS6", product: "Hoffman wash-down enclosure", current: "—", proposed: "CSA Type 4X", source: "Marketing page; CSA register no match", tier: 2 },
      { sku: "ENC-C1102", product: "Encore XHHW-2 copper", current: "—", proposed: "UL 44 listed", source: "Marketing page; file number absent", tier: 2 },
    ],
  },
];

/** The policy each decision writes, keyed by class then action. */
export const RULES: RuleBook = {
  volt: {
    accept: "NORMALIZE Voltage → \"{n} V\" WHERE source.tier = 1 AND corroboration ≥ 2",
    demote: "HOLD Voltage WHERE source = manufacturer_pdf — manual review required",
  },
  mfr: {
    accept: "MAP Manufacturer VIA alias_table WHERE exact_match; ELSE route to review",
    demote: "HOLD Manufacturer — alias table must be re-approved before auto-mapping",
  },
  nema: {
    accept: "SNAP Enclosure Rating → NEMA enum WHERE exact enum member; ELSE demote",
    demote: "HOLD Enclosure Rating — enum coercion disabled",
  },
  awg: {
    accept: "NORMALIZE Conductor Size → \"{n} AWG\"; route kcmil separately",
    demote: "HOLD Conductor Size — manual review required",
  },
  amp: {
    accept: "ACCEPT Ampacity WHERE 2 independent spec tables return the same figure",
    demote: "HOLD Ampacity — PDF table extraction not trusted for this catalog",
  },
  weight: {
    accept: "CONVERT Shipping Weight → lb, 2dp, WHERE source figure is cited",
    demote: "HOLD Shipping Weight — conversions require steward sign-off",
  },
  upc: {
    accept: "ACCEPT UPC WHERE GTIN-12 check digit validates; ELSE hold",
    demote: "HOLD UPC — all barcode writes require steward sign-off",
  },
  conduit: {
    accept: "NORMALIZE Trade Size → decimal in, retain trade designation",
    demote: "HOLD Trade Size — manual review required",
  },
  schema: {
    accept: "MERGE {Diameter, Outside Diameter, Width} → Diameter for conduit & conductor families",
    route: "ESCALATE schema collision to taxonomy owner before any write",
  },
  temp: {
    accept: "SPLIT Temperature Rating → {dry, wet}; block single-value writes",
    route: "ESCALATE conflicting ratings to the product data owner",
  },
  material: {
    accept: "ACCEPT inferred Enclosure Material WHERE part-number suffix is in the mapped set",
    route: "ESCALATE inferred materials — no write without a spec source",
  },
  desc: {
    accept: "TRUNCATE Long Description at last full clause ≤ channel limit {ERP 240, EDI 80}",
    route: "ESCALATE description policy to the channel owner",
  },
  coo: {
    accept: "OVERRIDE — Country of Origin accepted from tier-3 source (logged, reversible)",
    route: "NEVER auto-accept Country of Origin below source tier 1 — owner: trade compliance",
  },
  unspsc: {
    accept: "OVERRIDE — uncited UNSPSC codes written (logged, reversible)",
    route: "NEVER write UNSPSC without a source document — owner: catalog manager",
  },
  ul: {
    accept: "OVERRIDE — unverified safety listings published (logged, reversible)",
    route: "NEVER publish a safety listing absent from the certifying register — owner: compliance",
  },
};
